# Generated by Django 3.2.8 on 2021-10-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-uploaded',)},
        ),
        migrations.AlterField(
            model_name='note',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
